services:
  - type: web
    name: lavajato-kanban
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lavajato.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lavajato.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-service-name.onrender.com
