services:
  - type: web
    name: lavajato
    env: python
    buildCommand: ""
    startCommand: lavajato.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: lavajato.settings
      - key: DJANGO_SETTINGS_MODULE
        value: lavajato.settings
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
        value: your-service-name.onrender.com
