services:
  - type: web
    name: lavajato
    env: python
    buildCommand: ""
    startCommand: gunicorn lavajato.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: lavajato.settings
      - key: DJANGO_SETTINGS_MODULE
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-service-name.onrender.com
