# Generated by Django 5.2.2 on 2025-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('servico', models.CharField(choices=[('simples', 'Lavagem Simples'), ('completa', 'Lavagem Completa'), ('higienizacao', 'Higienização')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('chegada', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.CharField(choices=[('aguardando', 'Aguardando Atendimento'), ('externa', 'Lavagem Externa'), ('interna', 'Limpeza Interna'), ('finalizacao', 'Finalização'), ('pronto', 'Pronto para Entrega')], default='aguardando', max_length=20)),
            ],
        ),
    ]
